### ISSUE TITLE
Switch scraper season to 2021

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/player-scores#32]
After pinning the scraper season to 2020, we need to change the pipeline to switch to season 2021 consistently. Things to have into account

* We need to change the scraper season to 2021
* We need to start saving snapshots in S3 in a separate prefix
* We need to update the fetch step to collect data so that multiple seasons are considered
* We need to update the prep step so that multiple seasons are considered

Questions

- Assuming we can parameterize a scraper run for a particular season, we will have disconnected datasets for clubs, players, games and appearances for each season. (done in https://github.com/dcaribou/transfermarkt-scraper/pull/19)
    - How to merge them?
    - Where to merge them? Scraper? Player Scores?

**Comment by franz101** [comment]
Hey do you need help here? I have written a scraper that saves snapshots on S3.

**Comment by dcaribou** [comment]
Hey @franz101. I'd definitely welcome help on this, yes. Thanks for offering 😄

> I have written a scraper that saves snapshots on S3.

Can you explain more?

I recently did the changes on the scraper to support passing a `SEASON` parameter that get embedded in the URLs for the scraper (https://github.com/dcaribou/transfermarkt-scraper/pull/19). For example, the scraper can be invoked now collect the data for one particular season with

```console
> scrapy crawl clubs -a parents=samples/leagues.json -s SEASON=2020
{"type": "club", "href": "/manchester-city/startseite/verein/281", "parent": {"type": "league", "href": "/premier-league/startseite/wettbewerb/GB1", "seasoned_href": "https://www.transfermarkt.co.uk/premier-league/startseite/wettbewerb/GB1/plus/0?saison_id=2020"}}
{"type": "club", "href": "/inter-mailand/startseite/verein/46", "parent": {"type": "league", "href": "/serie-a/startseite/wettbewerb/IT1", "seasoned_href": "https://www.transfermarkt.co.uk/serie-a/startseite/wettbewerb/IT1/plus/0?saison_id=2020"}}
{"type": "club", "href": "/fc-liverpool/startseite/verein/31", "parent": {"type": "league", "href": "/premier-league/startseite/wettbewerb/GB1", "seasoned_href": "https://www.transfermarkt.co.uk/premier-league/startseite/wettbewerb/GB1/plus/0?saison_id=2020"}}
{"type": "club", "href": "/fc-chelsea/startseite/verein/631", "parent": {"type": "league", "href": "/premier-league/startseite/wettbewerb/GB1", "seasoned_href": "https://www.transfermarkt.co.uk/premier-league/startseite/wettbewerb/GB1/plus/0?saison_id=2020"}}
...
```

However the changes on the data pipeline to call the scraper for a set of seasons, and the changes on the prep steps to merge the raw scraped data from multiple seasons into the same datasets (`players`, `appearances`, `games`, etc.) are pending. These are the purpose of this issue.

The way I currently envision the required changes to get this right would be
1. Enhancing the `acquiring.py` script to accept a `season` or `season-range` argument. The script would then acquire and store the data for a particular season or set of seasons in different subfolders in `raw` 
<img width="220" alt="Screenshot 2021-06-15 at 13 09 09" src="https://user-images.githubusercontent.com/16071835/122042799-e4325300-cdda-11eb-89bc-e73df2d7d8a4.png">

2. In the `prep` stage, the raw data for the different seasons is combined into one single file per entity. One possible strategy for combining the raw assets can be
  - For appearances and games, simply append all seasons to the `appearances.csv` and `games.csv` "prepared" files
  - For players and clubs, append + deduplicate clubs and players by their ID to form the `clubs.csv` and `players.csv`

I am open to suggestions though.

**Comment by dcaribou** [comment]
Update on this issue

After the several updates to add historical data in #12, switching to season 2021 it should be as simple as changing the season parameter in the acquiring step in
https://github.com/dcaribou/player-scores/blob/139210f4ea55e2f999c133bb0f55a90e52373273/run_pipeline.sh#L9

We shall update this once season 2021 is available in Transfermarkt. As of today (2021-07-09) season 2021 is still not available.
